name: tada
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1


environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  

    
  get: ^4.6.5
  intl: ^0.19.0
  url_launcher: ^6.3.1

  smooth_page_indicator: ^1.2.1
  firebase_core: ^2.24.2
  flutter_native_splash: ^2.4.5
  json_annotation: ^4.8.1
  google_sign_in: ^6.2.1
  iconsax: ^0.0.8
  get_storage: ^2.1.1

  adaptive_theme: ^3.7.0

  #Iconsax
  iconsax_flutter: ^1.0.0
  iconsax_plus: ^1.0.0
  
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.16.0
  http: ^1.1.0
  logger: ^2.0.1
  lottie: ^3.3.1
  connectivity_plus: ^6.1.3
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  persistent_bottom_nav_bar: any
  persistent_bottom_nav_bar_v2: ^5.3.1

  provider: ^6.1.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  forui: ^0.10.0+1
  shadcn_ui: ^0.24.0
  google_fonts: ^6.2.1


  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  
  shadcn_flutter: ^0.0.34

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3



flutter_launcher_icons:
  image_path: "assets/icon/cat.png"
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  android_adaptive_icon_background: "#ff6c1f"
  android_adaptive_icon_foreground: "assets/icon/cat.png"
  padding: 0
  min_sdk_android: 21
  


flutter:
  uses-material-design: true


assets:
   - assets/animations/
   - assets/fonts/
   - assets/illustrations/
   - assets/logo/
   - assets/icon/

fonts: 
  - family: RobotoMono
    fonts:
      - asset: assets/fonts/RobotoMono-Regular.ttf
        weight: 400
  - family: Roboto
    fonts:
      - asset: assets/fonts/Roboto-Regular.ttf   
        weight: 400
      - asset: assets/fonts/Roboto-Light.ttf
        weight: 300
      - asset: assets/fonts/Roboto-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Roboto-Medium.ttf
        weight: 500
      - asset: assets\fonts\Roboto-LightItalic.ttf
        weight: 300
