name: tada
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1


environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  flutter_calendar_carousel: ^2.3.0
    
  get: ^4.6.5
  intl: ^0.19.0
  url_launcher: ^6.3.1

  smooth_page_indicator: ^1.2.1

  flutter_native_splash: ^2.4.6
  json_annotation: ^4.8.1

  #Firebase AUth and DB
  iconsax: ^0.0.8
  get_storage: ^2.1.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  google_sign_in: ^6.2.1

  #Hive DB
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0

  adaptive_theme: ^3.7.0

  #Iconsax
  iconsax_flutter: ^1.0.0
  iconsax_plus: ^1.0.0

  http: ^1.1.0
  logger: ^2.0.1

  connectivity_plus: ^6.1.3
  json_serializable: ^6.7.1
  build_runner: ^2.4.8

  provider: ^6.1.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  forui: ^0.10.0+1
  google_fonts: ^6.2.1




  flutter_floating_bottom_bar: ^1.3.0
  custom_sliding_segmented_control: ^1.8.5
  introduction_screen: ^3.1.17
  
  lottie: ^3.3.1

  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  hive_ce_generator: ^1.8.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/animations/
    - assets/fonts/
    - assets/illustrations/
    - assets/logo/
    - assets/icon/
    - assets/images/