// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAXqhny1oR7OeSBcoqBAlxW59HnqUe_F8',
    appId: '1:68909437012:android:8936cec4dc105e62af5dc1',
    messagingSenderId: '68909437012',
    projectId: 'tada-9760b',
    storageBucket: 'tada-9760b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN25As6fZdCZSy4PD38_ZMAk0yiaTSJjI',
    appId: '1:68909437012:ios:e970205922cb0d49af5dc1',
    messagingSenderId: '68909437012',
    projectId: 'tada-9760b',
    storageBucket: 'tada-9760b.firebasestorage.app',
    androidClientId: '68909437012-f7kcbofmb0nt372cnc7e8933pedk9d7o.apps.googleusercontent.com',
    iosClientId: '68909437012-aaanl63mt7581g33mpvm70kuvjdkt745.apps.googleusercontent.com',
    iosBundleId: 'com.example.tada',
  );

}